; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATmega4808]
platform = atmelmegaavr
board = ATmega4808
framework = arduino
board_build.variant = 28pin-standard

; Clock frequency in [Hz]
board_build.f_cpu = 16000000L
; Oscillator type (internal or external)
board_hardware.oscillator = internal

; Unflag build flags
build_unflags =
; Extra build flags
; https://github.com/sparkfun/SparkFun_u-blox_GNSS_v3/blob/main/src/u-blox_GNSS.h#L53-L69
build_flags =
    -Wl,-u,vfprintf
    -lprintf_flt
    -lm
    -D DEBUG_CALCULATION
;     -D DEBUG
;    -D SFE_UBLOX_REDUCED_PROG_MEM
;    -D SFE_UBLOX_DISABLE_AUTO_NMEA
;    -D SFE_UBLOX_DISABLE_RTCM_LOGGING
;    -D SFE_UBLOX_DISABLE_RAWX_SFRBX_PMP_QZSS_SAT
;    -D SFE_UBLOX_DISABLE_ESF
;    -D SFE_UBLOX_DISABLE_HNR

; Monitor port is auto-detected. Override here
monitor_port = /dev/cu.usbserial*
monitor_speed = 115200
monitor_dtr = 0
monitor_echo = yes
monitor_filters = send_on_enter, time, colorize, log2file

upload_protocol = serialupdi
upload_port = /dev/cu.usbserial*
upload_speed = 230400
upload_flags =
    -xrtsdtr=high
    -v

; Hardware settings
board_hardware.bod = 2.7v
board_hardware.eesave = yes
board_hardware.uart = no_bootloader
; board_hardware.uart = uart2
board_hardware.rstpin = reset


lib_deps =
    jchristensen/JC_Button@^2.1.5
    mikalhart/TinyGPSPlus@^1.1.0
    jeremycole/I2C Temperature Sensors derived from the LM75@^1.0.3
    robtillaart/DAC8571@^0.1.3
    mathertel/RotaryEncoder@^1.6.0
    duinowitchery/hd44780@^1.3.2
    robtillaart/I2C_EEPROM@^1.9.4
; sparkfun/SparkFun u-blox GNSS v3@^3.1.13
